### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by X-Mort-X** [nicosuave/siriproxy-arduino#1]
Iv been trying to use this plugin with elvisimpersonator's siriproxy and iv loaded it onto my pi successfully but most of the time i get an error..... 
'[Error] Failed to load plugin: Arduino reason: Dino::BoardNotFound'
Sometimes it seems to work perfectly but not often at all, anyone able to help?

**Comment by nicosuave** [comment]
I currently don't have an Arduino board in my possession. I will look into this for you however, @X-Mort-X. I should have some time before the weekend.

**Comment by X-Mort-X** [comment]
its okay! I went over to austinbv's git and it turns out that the problem most likely lies with dino! But version 0.11.3 has just been posted on github which should solve the problem so I shall let you know if it does when austinbv pushes the gem! saves you having to search through code blind or having to get an arduino :)

**Comment by nicosuave** [comment]
Ah, that makes sense. Thanks for the updates, man! I've been meaning to tinker with my buddy's Arduino this weekend, anyhow.

**Comment by X-Mort-X** [comment]
Well let me know how you get on when you do! I'd like to know if its just the mega thats having the problem! But its not gunna make a difference hopefully when 0.11.3 is pushed :)

**Comment by X-Mort-X** [comment]
your plugin will most likely stop working when version 0.11.3 is pushed as far as I can figure! I have it working with 0.12.0 by deleting the dino master and installing the 0.12.0  branch then changing the gemfile.lock to point to 0.12.0 :)

**Comment by X-Mort-X** [comment]
....also how would I add custom configurations like say read analogue pin A8?? as an example lol

**Comment by nicosuave** [comment]
This is quite stale and this repo is dead
